name: Code Checks
on:
    pull_request:
        types: [opened, synchronize, ready_for_review]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    phpcs:
        if: github.event.pull_request.draft == false
        uses: macrosbysara/shared-github-actions/.github/workflows/phpcs.yml@main

    final-check:
        needs: [phpcs]
        runs-on: ubuntu-latest
        if: always() && github.event.pull_request.draft == false
        steps:
            - name: Verify all checks passed
              run: |
                  results="${{ needs.phpcs.result }}"
                  echo "Job results: $results"

                  if [[ "$results" =~ failure ]]; then
                    echo "❌ One or more checks failed."
                    exit 1
                  fi

                  if [[ "$results" =~ cancelled ]]; then
                    echo "⚠️ One or more checks were cancelled."
                    exit 1
                  fi

                  echo "✅ All checks passed or were skipped."
